import type { Metadata, Viewport } from 'next';
import '../styles/tokens/index.css';
import '../styles/global.css';
import '../styles/dashboard.css';
import '../styles/wa-connect.css';
import Providers from './Providers';
import { ServiceWorkerRegistration } from '../components/shared/ServiceWorkerRegistration';

// Next.js 14+: themeColor must live on the viewport export, not metadata.
// Moving it here also fixes the existing "Unsupported metadata themeColor"
// build warning that surfaced on every admin page.
export const viewport: Viewport = {
  themeColor: '#0D9B6A',
};

export const metadata: Metadata = {
  metadataBase: new URL('https://gully-bite.vercel.app'),
  title: 'GullyBite — WhatsApp Ordering for Indian Restaurants. Zero Commission.',
  description:
    "GullyBite turns WhatsApp into your restaurant's ordering engine. Zero commission, flat ₹2,999/month, weekly auto-settlements. Go live in 10 minutes.",
  applicationName: 'GullyBite Dashboard',
  // /manifest.webmanifest is auto-generated by app/manifest.ts. Replaces
  // the legacy public/manifest.json (deleted).
  manifest: '/manifest.webmanifest',
  appleWebApp: {
    capable: true,
    statusBarStyle: 'default',
    title: 'GullyBite',
  },
  formatDetection: { telephone: false },
  openGraph: {
    title: 'GullyBite — WhatsApp Ordering for Indian Restaurants',
    description:
      'Zero commission. Flat ₹2,999/month. Own your customers. Live in 10 minutes.',
    type: 'website',
    images: ['/og-image.png'],
  },
  twitter: {
    card: 'summary_large_image',
  },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
        <ServiceWorkerRegistration />
      </body>
    </html>
  );
}
