#!/usr/bin/env tsx
//
// Generator. Reads packages/design-tokens/src/* and writes:
//   1. frontend/src/styles/_generated/tokens.css
//   2. staff-app/src/styling/_generated/tokens.ts
//
// Both outputs start with a banner. Both are overwritten on every run.
// Run via `npm run tokens:gen` from repo root.

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  primitives,
  overlays,
  semanticLanding,
  semanticDashboard,
  landingExtras,
  type SemanticToken,
} from '../src/colors';
import { fontFamilies, sizes, weights, lineHeights } from '../src/typography';
import { spacing } from '../src/spacing';
import { radii, rAlias } from '../src/radii';
import { shadowsWeb, shadowsSemantic, elevation } from '../src/shadows';
import { zIndex, containers } from '../src/layout';
import { breakpoints } from '../src/breakpoints';
import { card, button, input, modal } from '../src/components';
import nativeTokens from '../src/native';

const __filename = fileURLToPath(import.meta.url);
const __dirname  = dirname(__filename);
const REPO_ROOT  = resolve(__dirname, '../../..');

const CSS_OUT = resolve(REPO_ROOT, 'frontend/src/styles/_generated/tokens.css');
const TS_OUT  = resolve(REPO_ROOT, 'staff-app/src/styling/_generated/tokens.ts');

const BANNER = '/* GENERATED by @gullybite/design-tokens — do not edit; run `npm run tokens:gen` */';

// ─── CSS emit helpers ────────────────────────────────────────────────────

// Flatten a nested primitive group like { neutral: { '0': '#fff', '100': '#…' } }
// into [['gb-neutral-0','#fff'], ['gb-neutral-100','#…'], …]. String leaves are
// emitted verbatim (e.g. `cream: '#FAF8F3'` becomes `--gb-cream`).
//
// The `gb-` prefix matches the live frontend/src/styles/tokens/colors.css
// names so the generated tokens.css is a drop-in replacement.
function flattenPrimitives(): Array<[string, string]> {
  const out: Array<[string, string]> = [];
  for (const [group, val] of Object.entries(primitives)) {
    if (typeof val === 'string') {
      out.push([`gb-${group}`, val]);
    } else {
      for (const [shade, hex] of Object.entries(val as Record<string, string>)) {
        out.push([`gb-${group}-${shade}`, hex as string]);
      }
    }
  }
  return out;
}

function flattenOverlays(): Array<[string, string]> {
  return Object.entries(overlays).map(([key, val]) => [`overlay-${kebab(key)}`, val as string]);
}

// `Foo Bar` → `foo-bar`, `accGlowLanding` → `acc-glow-landing`
function kebab(s: string): string {
  return s.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
}

// Resolve a semantic token's `ref` into a CSS `var(--…)` reference.
// `ref` syntax:
//   'neutral.0'               → var(--gb-neutral-0)
//   'overlays.modal'          → var(--overlay-modal)
//   'overlays.accGlowLanding' → var(--overlay-acc-glow-landing)
// Tokens with `ref: null` emit the literal value.
function semanticToCss(tok: SemanticToken): string {
  if (!tok.ref) return tok.value;
  const [head, ...rest] = tok.ref.split('.');
  if (head === 'overlays') {
    return `var(--overlay-${kebab(rest.join('.'))})`;
  }
  // Otherwise it's a primitive group — emit `--gb-{group}-{shade}`.
  return `var(--gb-${head}-${rest.join('-')})`;
}

function emitVarLines(pairs: Array<[string, string]>, indent = '  '): string {
  return pairs.map(([k, v]) => `${indent}--${k}: ${v};`).join('\n');
}

function emitSemanticBlock(map: Record<string, SemanticToken>, indent = '  '): string {
  // Semantic tokens emit as plain `--{key}` (no namespace prefix), matching
  // the live names in frontend/src/styles/tokens/colors.css and
  // dashboard.css :root override (--acc, --surface, --rim, --tx, etc.).
  return Object.entries(map)
    .map(([key, tok]) => `${indent}--${key}: ${semanticToCss(tok)};`)
    .join('\n');
}

// ─── CSS emit — sections ─────────────────────────────────────────────────

function sectionPrimitives(): string {
  const lines = emitVarLines(flattenPrimitives());
  return `  /* ── Primitives ──────────────────────────────────────────── */\n${lines}`;
}

function sectionOverlays(): string {
  const lines = emitVarLines(flattenOverlays());
  return `  /* ── Overlays ─────────────────────────────────────────────── */\n${lines}`;
}

function sectionSemantic(label: string, map: Record<string, SemanticToken>): string {
  return `  /* ── Semantic — ${label} ───────────────────────────────────── */\n${emitSemanticBlock(map)}`;
}

function sectionTypography(): string {
  const lines: Array<[string, string]> = [];
  lines.push(['font-sans', fontFamilies.sans]);
  lines.push(['font-head', fontFamilies.head]);
  lines.push(['font-body', fontFamilies.body]);
  lines.push(['font-mono', fontFamilies.mono]);
  for (const [key, val] of Object.entries(sizes)) {
    lines.push([`text-${key}`, (val as { css: string }).css]);
  }
  for (const [key, val] of Object.entries(weights)) {
    lines.push([`weight-${kebab(key)}`, String(val)]);
  }
  for (const [key, val] of Object.entries(lineHeights)) {
    lines.push([`leading-${kebab(key)}`, String(val)]);
  }
  return `  /* ── Typography ───────────────────────────────────────────── */\n${emitVarLines(lines)}`;
}

function sectionSpacing(): string {
  const lines = Object.entries(spacing).map(
    ([k, v]) => [`space-${k}`, (v as { css: string }).css] as [string, string]
  );
  return `  /* ── Spacing ──────────────────────────────────────────────── */\n${emitVarLines(lines)}`;
}

function sectionRadii(rContext: 'landing' | 'dashboard'): string {
  const lines: Array<[string, string]> = [];
  for (const [key, val] of Object.entries(radii)) {
    lines.push([`radius-${kebab(key)}`, (val as { css: string }).css]);
  }
  // --r alias differs per surface.
  lines.push(['r', `var(--radius-${rAlias[rContext].ref})`]);
  return `  /* ── Radii ────────────────────────────────────────────────── */\n${emitVarLines(lines)}`;
}

function sectionShadowsPrimitives(): string {
  const lines: Array<[string, string]> = [];
  for (const [scale, set] of Object.entries(shadowsWeb)) {
    for (const [size, val] of Object.entries(set)) {
      lines.push([`shadow-${scale}-${size}`, val as string]);
    }
  }
  return `  /* ── Shadow primitives ────────────────────────────────────── */\n${emitVarLines(lines)}`;
}

function sectionShadowsSemantic(surface: 'landing' | 'dashboard'): string {
  const set = shadowsSemantic[surface];
  const lines: Array<[string, string]> = [];
  for (const [size, tok] of Object.entries(set)) {
    const ref = (tok as { ref: string }).ref; // e.g. 'soft.sm'
    lines.push([`shadow-${size}`, `var(--shadow-${kebab(ref.replace('.', '-'))})`]);
  }
  // Symmetric --shadow alias (== --shadow-md) for callers that read --shadow.
  const md = lines.find(([k]) => k === 'shadow-md');
  if (md) lines.push(['shadow', md[1]]);
  return `  /* ── Shadow aliases (${surface}) ───────────────────────────── */\n${emitVarLines(lines)}`;
}

function sectionLayout(): string {
  const lines: Array<[string, string]> = [];
  for (const [key, val] of Object.entries(zIndex)) {
    lines.push([`z-${kebab(key)}`, String(val)]);
  }
  for (const [key, val] of Object.entries(containers)) {
    lines.push([`container-${kebab(key)}`, `${val}px`]);
  }
  return `  /* ── Layout ───────────────────────────────────────────────── */\n${emitVarLines(lines)}`;
}

function sectionBreakpoints(): string {
  const lines = Object.entries(breakpoints).map(
    ([k, v]) => [`bp-${k}`, `${v}px`] as [string, string]
  );
  return `  /* ── Breakpoints (raw values; CSS @media uses literals) ───── */\n${emitVarLines(lines)}`;
}

function sectionComponents(): string {
  const lines: Array<[string, string]> = [];
  // Card
  lines.push(['card-padding-header',   card.paddingHeader]);
  lines.push(['card-padding-body',     card.paddingBody]);
  lines.push(['card-padding-fallback', card.paddingFallback]);
  lines.push(['card-padding-default',  card.paddingDefault]);
  lines.push(['card-radius',           `var(--r)`]);
  // Button
  lines.push(['button-padding-x-md', button.paddingX.md]);
  lines.push(['button-padding-x-sm', button.paddingX.sm]);
  lines.push(['button-padding-x-xs', button.paddingX.xs]);
  lines.push(['button-padding-y-md', button.paddingY.md]);
  lines.push(['button-padding-y-sm', button.paddingY.sm]);
  lines.push(['button-padding-y-xs', button.paddingY.xs]);
  lines.push(['button-font-size-md', button.fontSize.md]);
  lines.push(['button-font-size-sm', button.fontSize.sm]);
  lines.push(['button-font-size-xs', button.fontSize.xs]);
  lines.push(['button-min-height-md', button.minHeight.md]);
  lines.push(['button-min-height-xs', button.minHeight.xs]);
  lines.push(['button-radius',       `var(--radius-md)`]);
  lines.push(['button-gap',          button.gap]);
  // Input
  lines.push(['input-padding-x',     input.paddingX]);
  lines.push(['input-padding-y',     input.paddingY]);
  lines.push(['input-font-size',     input.fontSize]);
  lines.push(['input-radius',        `var(--radius-md)`]);
  // Modal
  lines.push(['modal-backdrop-color', `var(--overlay-modal)`]);
  lines.push(['modal-z-index',        `var(--z-modal)`]);
  return `  /* ── Component defaults ───────────────────────────────────── */\n${emitVarLines(lines)}`;
}

// ─── Build CSS ───────────────────────────────────────────────────────────

function buildCss(): string {
  const rootBlock = [
    sectionPrimitives(),
    sectionOverlays(),
    sectionSemantic('landing', semanticLanding),
    sectionSemantic('landing extras', landingExtras),
    sectionTypography(),
    sectionSpacing(),
    sectionRadii('landing'),
    sectionShadowsPrimitives(),
    sectionShadowsSemantic('landing'),
    sectionLayout(),
    sectionBreakpoints(),
    sectionComponents(),
  ].join('\n\n');

  const dashBlock = [
    sectionSemantic('dashboard overrides', semanticDashboard),
    `  /* ── Radii alias (dashboard) ──────────────────────────────── */\n  --r: var(--radius-${rAlias.dashboard.ref});`,
    sectionShadowsSemantic('dashboard'),
  ].join('\n\n');

  return [
    BANNER,
    '',
    ':root {',
    rootBlock,
    '}',
    '',
    // Dashboard semantic overrides land on a SECOND :root block (not a
    // [data-surface="dashboard"] selector). This matches the live
    // dashboard.css :root override pattern — the CSS cascade resolves
    // the second block as wholesale overrides for the same selector.
    // Landing/auth surfaces still reach indigo via --landing-* / --cta-*
    // tokens that aren't redefined here, so this doesn't blow away
    // landing branding.
    ':root {',
    dashBlock,
    '}',
    '',
  ].join('\n');
}

// ─── Build TS ────────────────────────────────────────────────────────────

function buildTs(): string {
  // JSON.stringify is enough — every leaf is a string / number / nested
  // object, and the consumer reads via the default export.
  const json = JSON.stringify(nativeTokens, null, 2);
  return [
    BANNER,
    '',
    '// Default export shape:',
    '//   tokens.colors.{primitives, overlays, semantic.{landing, dashboard}, surface,',
    '//                  landingExtras, statusBadge, subscriptionBadge}',
    '//   tokens.typography.{families, sizes, weights, lineHeights}',
    '//   tokens.spacing.{0..32}',
    '//   tokens.radii.{none..full, r}',
    '//   tokens.shadows.elevation.{0..5}',
    '//   tokens.layout.{zIndex, containers}',
    '//   tokens.breakpoints.{sm..3xl}',
    '//   tokens.components.{card, button, input, modal}',
    '',
    `const tokens = ${json} as const;`,
    '',
    'export default tokens;',
    '',
  ].join('\n');
}

// ─── Write ───────────────────────────────────────────────────────────────

function writeFile(path: string, content: string): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content, 'utf8');
  // eslint-disable-next-line no-console
  console.log(`wrote ${path}`);
}

writeFile(CSS_OUT, buildCss());
writeFile(TS_OUT, buildTs());
