/* GENERATED by @gullybite/design-tokens — do not edit; run `npm run tokens:gen` */

// Default export shape:
//   tokens.colors.{primitives, overlays, semantic.{landing, dashboard}, surface,
//                  landingExtras, statusBadge, subscriptionBadge}
//   tokens.typography.{families, sizes, weights, lineHeights}
//   tokens.spacing.{0..32}
//   tokens.radii.{none..full, r}
//   tokens.shadows.elevation.{0..5}
//   tokens.layout.{zIndex, containers}
//   tokens.breakpoints.{sm..3xl}
//   tokens.components.{card, button, input, modal}

const tokens = {
  "colors": {
    "primitives": {
      "neutral": {
        "0": "#ffffff",
        "50": "#f9fafb",
        "100": "#f3f4f6",
        "200": "#e5e7eb",
        "300": "#d1d5db",
        "400": "#9ca3af",
        "500": "#6b7280",
        "600": "#4b5563",
        "700": "#374151",
        "800": "#1f2937",
        "900": "#111827"
      },
      "slate": {
        "50": "#f8fafc",
        "100": "#f1f5f9",
        "200": "#e2e8f0",
        "300": "#cbd5e1",
        "400": "#94a3b8",
        "500": "#64748b",
        "600": "#475569",
        "700": "#334155",
        "800": "#1e293b",
        "900": "#0f172a"
      },
      "indigo": {
        "100": "#e0e7ff",
        "500": "#6366f1",
        "600": "#4f46e5",
        "700": "#4338ca",
        "800": "#3730a3"
      },
      "violet": {
        "600": "#7c3aed"
      },
      "teal": {
        "700": "#0F766E",
        "800": "#0D5F58",
        "700-glow": "rgba(15, 118, 110, 0.18)"
      },
      "green": {
        "50": "#E6F5EC",
        "100": "#C7E8D5",
        "300": "#5DBD8F",
        "500": "#0D9B6A",
        "600": "#078A5A",
        "700": "#04724A",
        "900": "#0A1F17"
      },
      "wa": {
        "500": "#16a34a",
        "600": "#15803d",
        "light": "#dcfce7",
        "brand": "#25D366",
        "brand-hover": "#1fbd5a"
      },
      "red": {
        "100": "#fee2e2",
        "200": "#fecaca",
        "300": "#fca5a5",
        "500": "#dc2626",
        "600": "#b91c1c",
        "900": "#991b1b"
      },
      "amber": {
        "100": "#fef3c7",
        "200": "#fde68a",
        "500": "#d97706",
        "600": "#b45309",
        "900": "#92400e"
      },
      "blue": {
        "100": "#dbeafe",
        "500": "#2563eb",
        "600": "#1d4ed8"
      },
      "orange": {
        "200": "#fed7aa",
        "500": "#F28D35"
      },
      "rose": {
        "50": "#fff1f2"
      },
      "cream": "#FAF8F3",
      "sand": "#F3EFE6",
      "brand": {
        "yellow": "#F9C303",
        "red": "#E42623",
        "green": "#0D5F3C",
        "green-hover": "#0A4A2E",
        "cream": "#F9F8F1"
      }
    },
    "overlays": {
      "modal": "rgba(0,0,0,0.5)",
      "modalTinted": "rgba(15,23,42,0.45)",
      "redGlow": "rgba(220,38,38,0.10)",
      "redStroke": "rgba(220,38,38,0.45)",
      "accGlowLanding": "rgba(79, 70, 229, .12)",
      "accGlowDashboard": "rgba(15, 118, 110, 0.18)",
      "waGlow": "rgba(22, 163, 74, .1)",
      "goldGlow": "rgba(217, 119, 6, .1)"
    },
    "semantic": {
      "landing": {
        "bg": "#f1f5f9",
        "bg2": "#ffffff",
        "surface": "#fff",
        "surface2": "#f1f5f9",
        "rim": "#e2e8f0",
        "rim2": "#cbd5e1",
        "tx": "#0f172a",
        "dim": "#64748b",
        "mute": "#94a3b8",
        "acc": "#4f46e5",
        "acc2": "#4338ca",
        "acc-glow": "rgba(79, 70, 229, .12)",
        "wa": "#16a34a",
        "wa-light": "#dcfce7",
        "gold": "#d97706",
        "red": "#dc2626"
      },
      "dashboard": {
        "ink": "#f8f9fb",
        "ink2": "#ffffff",
        "ink3": "#ffffff",
        "ink4": "#f3f4f6",
        "bg": "#f8f9fb",
        "bg2": "#ffffff",
        "surface": "#ffffff",
        "surface2": "#f3f4f6",
        "rim": "#e5e7eb",
        "rim2": "#d1d5db",
        "tx": "#111827",
        "dim": "#6b7280",
        "mute": "#9ca3af",
        "acc": "#0F766E",
        "acc2": "#0D5F58",
        "acc-glow": "rgba(15, 118, 110, 0.18)",
        "wa": "#16a34a",
        "wa2": "#15803d",
        "wa-glow": "rgba(22, 163, 74, .1)",
        "gold": "#d97706",
        "gold2": "#b45309",
        "gold-glow": "rgba(217, 119, 6, .1)",
        "red": "#dc2626",
        "blue": "#2563eb"
      }
    },
    "landingExtras": {
      "landing-hero-bg": "#F9F8F1",
      "landing-section-bg": "#F9F8F1",
      "landing-section-alt-bg": "#F3EFE6",
      "landing-dark-bg": "#0A1F17",
      "landing-ink": "#0A1F17",
      "landing-slate": "#334155",
      "landing-mute": "#64748b",
      "landing-line": "#e5e7eb",
      "cta-primary-bg": "#0D5F3C",
      "cta-primary-hover": "#0A4A2E",
      "cta-primary-text": "#ffffff",
      "cta-ghost-border": "#0A1F17",
      "cta-ghost-text": "#0A1F17",
      "cta-secondary-bg": "#F9C303",
      "cta-secondary-text": "#0A1F17",
      "landing-accent-yellow": "#F9C303",
      "landing-accent-red": "#E42623"
    },
    "surface": {
      "acc": "#0F766E",
      "acc2": "#0D5F58",
      "accGlow": "rgba(15, 118, 110, 0.18)",
      "ink": "#f8f9fb",
      "ink2": "#ffffff",
      "ink3": "#ffffff",
      "ink4": "#f3f4f6",
      "rim": "#e5e7eb",
      "rim2": "#d1d5db",
      "tx": "#111827",
      "dim": "#6b7280",
      "mute": "#9ca3af",
      "wa": "#16a34a",
      "wa2": "#15803d",
      "waGlow": "rgba(22, 163, 74, .1)",
      "gold": "#d97706",
      "gold2": "#b45309",
      "goldGlow": "rgba(217, 119, 6, .1)",
      "red": "#dc2626",
      "blue": "#2563eb",
      "purple": "#7c3aed"
    },
    "statusBadge": {
      "PENDING_PAYMENT": {
        "bg": "#fff7ed",
        "fg": "#c2410c",
        "label": "Pending Payment"
      },
      "pending": {
        "bg": "#fff7ed",
        "fg": "#c2410c",
        "label": "New"
      },
      "CONFIRMED": {
        "bg": "#dbeafe",
        "fg": "#1d4ed8",
        "label": "Confirmed"
      },
      "confirmed": {
        "bg": "#dbeafe",
        "fg": "#1d4ed8",
        "label": "Confirmed"
      },
      "PREPARING": {
        "bg": "#fef3c7",
        "fg": "#b45309",
        "label": "Preparing"
      },
      "preparing": {
        "bg": "#fef3c7",
        "fg": "#b45309",
        "label": "Preparing"
      },
      "PACKED": {
        "bg": "#d1fae5",
        "fg": "#15803d",
        "label": "Ready"
      },
      "ready": {
        "bg": "#d1fae5",
        "fg": "#15803d",
        "label": "Ready"
      },
      "DISPATCHED": {
        "bg": "#ede9fe",
        "fg": "#6d28d9",
        "label": "Out for Delivery"
      },
      "out_for_delivery": {
        "bg": "#ede9fe",
        "fg": "#6d28d9",
        "label": "Out for Delivery"
      },
      "DELIVERED": {
        "bg": "#f3f4f6",
        "fg": "#4b5563",
        "label": "Delivered"
      },
      "delivered": {
        "bg": "#f3f4f6",
        "fg": "#4b5563",
        "label": "Delivered"
      },
      "CANCELLED": {
        "bg": "#fee2e2",
        "fg": "#b91c1c",
        "label": "Cancelled"
      },
      "cancelled": {
        "bg": "#fee2e2",
        "fg": "#b91c1c",
        "label": "Cancelled"
      }
    },
    "subscriptionBadge": {
      "active": {
        "bg": "#dcfce7",
        "fg": "#15803d"
      },
      "paused": {
        "bg": "#fee2e2",
        "fg": "#b91c1c"
      },
      "default": {
        "bg": "#f3f4f6",
        "fg": "#4b5563"
      }
    }
  },
  "typography": {
    "families": {
      "sans": "'Plus Jakarta Sans', system-ui, sans-serif",
      "head": "'Plus Jakarta Sans', system-ui, -apple-system, sans-serif",
      "body": "'Plus Jakarta Sans', system-ui, -apple-system, sans-serif",
      "mono": "ui-monospace, 'SF Mono', Menlo, monospace"
    },
    "sizes": {
      "xs": 11.5,
      "sm": 13,
      "base": 14,
      "md": 15,
      "lg": 17,
      "xl": 20,
      "2xl": 26,
      "3xl": 32,
      "4xl": 58
    },
    "weights": {
      "regular": 400,
      "medium": 500,
      "semibold": 600,
      "bold": 700,
      "extrabold": 800
    },
    "lineHeights": {
      "tight": 1.1,
      "snug": 1.3,
      "normal": 1.5,
      "relaxed": 1.65,
      "loose": 1.75
    }
  },
  "spacing": {
    "0": 0,
    "1": 4,
    "2": 8,
    "3": 12,
    "4": 16,
    "5": 20,
    "6": 24,
    "7": 28,
    "8": 32,
    "10": 40,
    "12": 48,
    "14": 56,
    "16": 64,
    "20": 80,
    "24": 96,
    "32": 128
  },
  "radii": {
    "none": 0,
    "sm": 6,
    "md": 8,
    "lg": 10,
    "xl": 12,
    "2xl": 16,
    "3xl": 20,
    "full": 9999,
    "r": 12
  },
  "shadows": {
    "elevation": {
      "0": {
        "shadowColor": "#000",
        "shadowOffset": {
          "width": 0,
          "height": 0
        },
        "shadowOpacity": 0,
        "shadowRadius": 0,
        "elevation": 0
      },
      "1": {
        "shadowColor": "#000",
        "shadowOffset": {
          "width": 0,
          "height": 1
        },
        "shadowOpacity": 0.06,
        "shadowRadius": 2,
        "elevation": 1
      },
      "2": {
        "shadowColor": "#000",
        "shadowOffset": {
          "width": 0,
          "height": 2
        },
        "shadowOpacity": 0.07,
        "shadowRadius": 4,
        "elevation": 3
      },
      "3": {
        "shadowColor": "#000",
        "shadowOffset": {
          "width": 0,
          "height": 4
        },
        "shadowOpacity": 0.08,
        "shadowRadius": 8,
        "elevation": 6
      },
      "4": {
        "shadowColor": "#000",
        "shadowOffset": {
          "width": 0,
          "height": 8
        },
        "shadowOpacity": 0.1,
        "shadowRadius": 16,
        "elevation": 12
      },
      "5": {
        "shadowColor": "#000",
        "shadowOffset": {
          "width": 0,
          "height": 16
        },
        "shadowOpacity": 0.14,
        "shadowRadius": 24,
        "elevation": 18
      }
    }
  },
  "layout": {
    "zIndex": {
      "base": 0,
      "dropdown": 100,
      "sticky": 200,
      "overlay": 300,
      "modal": 400,
      "popover": 500,
      "toast": 600,
      "tooltip": 700
    },
    "containers": {
      "narrow": 640,
      "base": 960,
      "wide": 1120,
      "max": 1280
    }
  },
  "breakpoints": {
    "sm": 480,
    "md": 640,
    "lg": 768,
    "xl": 900,
    "2xl": 960,
    "3xl": 1024
  },
  "components": {
    "card": {
      "paddingDefault": "1.3rem"
    },
    "button": {
      "height": {
        "sm": 28,
        "md": 36,
        "lg": 44
      },
      "gap": 6
    },
    "input": {
      "height": 40
    },
    "modal": {
      "backdropColor": "rgba(0,0,0,0.5)",
      "zIndex": 400
    }
  }
} as const;

export default tokens;
